import type { NextPage } from "next"
import React, { useState, useCallback } from "react"
import Head from "next/head"
import Image from "next/image"
import styles from "../../styles/Home.module.css"
import { axiosApi } from "../client"
import { BaseUserDto } from "../api"

const Home: NextPage = () => {
  const [nameText, setNameText] = useState("")
  const [emailText, setEmailText] = useState("")
  const [passwordText, setPasswordText] = useState("")
  const [user, setUser] = useState<BaseUserDto[]>()
  const onChangeNameText = (event: React.ChangeEvent<HTMLInputElement>): void =>
    setNameText(event.target.value)
  const onChangeEmailText = (
    event: React.ChangeEvent<HTMLInputElement>
  ): void => setEmailText(event.target.value)
  const onChangePasswordText = (
    event: React.ChangeEvent<HTMLInputElement>
  ): void => setPasswordText(event.target.value)

  const findAllUser = useCallback(() => {
    const allUser = async () => {
      const allUser = await axiosApi.userControllerIndex().then((res) => {
        return res.data
      })
      await setUser(allUser)
    }
    allUser()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button alia-label="findAllUser" type="button" onClick={findAllUser}>
            findAllUser
          </button>
          {user ? (
            <ul>
              {user.map((u, i) => (
                <li key={i}>
                  {u.name}
                  {u.email}
                </li>
              ))}
            </ul>
          ) : null}
          <input
            placeholder={"nameを入力してください"}
            type={"text"}
            value={nameText}
            onChange={onChangeNameText}
          />
          <input
            placeholder={"emailを入力してください"}
            type={"text"}
            value={emailText}
            onChange={onChangeEmailText}
          />
          <input
            placeholder={"passwordを入力してください"}
            type={"text"}
            value={passwordText}
            onChange={onChangePasswordText}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
